from enum import IntEnum

GARMIN_BASE_UUID = "6A4E{:04X}-667B-11E3-949A-0800200C9A66"
CLIENT_ID = 2

class GarminService(IntEnum):
    GFDI = 1
    REGISTRATION = 4
    REALTIME_HR = 6
    REALTIME_STEPS = 7
    REALTIME_CALORIES = 8
    REALTIME_INTENSITY = 10
    REALTIME_HRV = 12
    REALTIME_STRESS = 13
    REALTIME_ACCELEROMETER = 16
    REALTIME_SPO2 = 19
    REALTIME_BODY_BATTERY = 20
    REALTIME_RESPIRATION = 21

class SystemEventType(IntEnum):
    """GFDI system-event types (message 5030).

    Only the values this library sends or acts on are named; the rest arrive as
    raw integers on :class:`~garmin_ble.events.SystemEvent`.
    """

    SYNC_COMPLETE = 0
    SYNC_FAIL = 1
    TIME_UPDATED = 16


class RequestType(IntEnum):
    REGISTER_ML_REQ = 0
    REGISTER_ML_RESP = 1
    CLOSE_HANDLE_REQ = 2
    CLOSE_HANDLE_RESP = 3
    CLOSE_ALL_REQ = 5
    CLOSE_ALL_RESP = 6

class GarminMessage(IntEnum):
    RESPONSE = 5000
    DOWNLOAD_REQUEST = 5002
    UPLOAD_REQUEST = 5003
    FILE_TRANSFER_DATA = 5004
    CREATE_FILE = 5005
    FILTER = 5007
    SET_FILE_FLAG = 5008
    FIT_DEFINITION = 5011
    FIT_DATA = 5012
    WEATHER_REQUEST = 5014
    DEVICE_INFORMATION = 5024
    DEVICE_SETTINGS = 5026
    SYSTEM_EVENT = 5030
    SUPPORTED_FILE_TYPES_REQ = 5031
    NOTIFICATION_UPDATE = 5033
    NOTIFICATION_CONTROL = 5034
    NOTIFICATION_DATA = 5035
    NOTIFICATION_SUBSCRIPTION = 5036
    SYNCHRONIZATION = 5037
    FIND_MY_PHONE_REQUEST = 5039
    FIND_MY_PHONE_CANCEL = 5040
    MUSIC_CONTROL = 5041
    MUSIC_CONTROL_CAPABILITIES = 5042
    PROTOBUF_REQUEST = 5043
    PROTOBUF_RESPONSE = 5044
    MUSIC_CONTROL_ENTITY_UPDATE = 5049
    CONFIGURATION = 5050
    CURRENT_TIME_REQUEST = 5052
    AUTH_NEGOTIATION = 5101
