from enum import IntEnum

GARMIN_BASE_UUID = "6A4E{:04X}-667B-11E3-949A-0800200C9A66"
CLIENT_ID = 2

class GarminService(IntEnum):
    GFDI = 1
    REGISTRATION = 4
    REALTIME_HR = 6
    REALTIME_STEPS = 7
    REALTIME_CALORIES = 8
    REALTIME_INTENSITY = 10
    REALTIME_HRV = 12
    REALTIME_STRESS = 13
    REALTIME_ACCELEROMETER = 16
    REALTIME_SPO2 = 19
    REALTIME_BODY_BATTERY = 20
    REALTIME_RESPIRATION = 21

class RequestType(IntEnum):
    REGISTER_ML_REQ = 0
    REGISTER_ML_RESP = 1
    CLOSE_HANDLE_REQ = 2
    CLOSE_HANDLE_RESP = 3
    CLOSE_ALL_REQ = 5
    CLOSE_ALL_RESP = 6
