# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: garmin_contacts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'garmin_contacts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15garmin_contacts.proto\x12\x06garmin\"K\n\x08Response\x12 \n\x07\x63ontact\x18\x01 \x03(\x0b\x32\x0f.garmin.Contact\x12\x1d\n\x04self\x18\x02 \x01(\x0b\x32\x0f.garmin.Contact\"\xd5\x01\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x66ullName\x18\x02 \x01(\t\x12\x11\n\tfirstName\x18\x03 \x01(\t\x12\x10\n\x08lastName\x18\x04 \x01(\t\x12\x1c\n\x05phone\x18\x05 \x03(\x0b\x32\r.garmin.Phone\x12\x0c\n\x04unk7\x18\x07 \x01(\t\x12\x0c\n\x04unk8\x18\x08 \x01(\r\x12\x0c\n\x04unk9\x18\t \x01(\r\x12\r\n\x05unk10\x18\n \x01(\r\x12\x12\n\nupdateTime\x18\x0b \x01(\x04\x12\r\n\x05unk12\x18\x0c \x01(\r\x12\r\n\x05unk21\x18\x15 \x01(\r\"\xc0\x01\n\x05Phone\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x0c\n\x04unk2\x18\x02 \x01(\r\x12\x0c\n\x04unk3\x18\x03 \x01(\r\x12\x0c\n\x04unk4\x18\x04 \x01(\r\x12\x0c\n\x04unk5\x18\x05 \x01(\r\x12\x0c\n\x04unk6\x18\x06 \x01(\r\x12\x0c\n\x04unk7\x18\x07 \x01(\r\x12\x0c\n\x04unk8\x18\x08 \x01(\t\x12\x0c\n\x04unk9\x18\t \x01(\r\x12\n\n\x02id\x18\n \x01(\t\x12\r\n\x05unk11\x18\x0b \x01(\r\x12\x1c\n\x05unk12\x18\x0c \x03(\x0b\x32\r.garmin.Unk12\"#\n\x05Unk12\x12\x0c\n\x04unk1\x18\x01 \x01(\r\x12\x0c\n\x04unk2\x18\x02 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'garmin_contacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE']._serialized_start=33
  _globals['_RESPONSE']._serialized_end=108
  _globals['_CONTACT']._serialized_start=111
  _globals['_CONTACT']._serialized_end=324
  _globals['_PHONE']._serialized_start=327
  _globals['_PHONE']._serialized_end=519
  _globals['_UNK12']._serialized_start=521
  _globals['_UNK12']._serialized_end=556
# @@protoc_insertion_point(module_scope)
