# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_ecg_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_ecg_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gdi_ecg_service.proto\x12\x11garmin_vivomovehr\"G\n\nEcgService\x12\x39\n\rfile_transfer\x18\x01 \x01(\x0b\x32\".garmin_vivomovehr.EcgFileTransfer\"\xf8\x02\n\x0f\x45\x63gFileTransfer\x12\x37\n\x0cinit_request\x18\x03 \x01(\x0b\x32!.garmin_vivomovehr.EcgInitRequest\x12\x39\n\rinit_response\x18\x04 \x01(\x0b\x32\".garmin_vivomovehr.EcgInitResponse\x12\x42\n\x12transfer_start_req\x18\x05 \x01(\x0b\x32&.garmin_vivomovehr.EcgTransferStartReq\x12\x42\n\x12transfer_start_ack\x18\x06 \x01(\x0b\x32&.garmin_vivomovehr.EcgTransferStartAck\x12,\n\x08\x65\x63g_file\x18\x07 \x01(\x0b\x32\x1a.garmin_vivomovehr.EcgFile\x12\x1e\n\x16transfer_finish_notify\x18\x08 \x01(\t\x12\x1b\n\x13transfer_finish_ack\x18\t \x01(\t\"\x1e\n\x0e\x45\x63gInitRequest\x12\x0c\n\x04unk1\x18\x01 \x01(\t\"\x1f\n\x0f\x45\x63gInitResponse\x12\x0c\n\x04unk1\x18\x01 \x01(\r\"#\n\x13\x45\x63gTransferStartReq\x12\x0c\n\x04unk1\x18\x01 \x01(\t\"#\n\x13\x45\x63gTransferStartAck\x12\x0c\n\x04unk2\x18\x02 \x01(\r\"A\n\x07\x45\x63gFile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04unk3\x18\x03 \x01(\r\x12\x0c\n\x04unk4\x18\x04 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_ecg_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECGSERVICE']._serialized_start=44
  _globals['_ECGSERVICE']._serialized_end=115
  _globals['_ECGFILETRANSFER']._serialized_start=118
  _globals['_ECGFILETRANSFER']._serialized_end=494
  _globals['_ECGINITREQUEST']._serialized_start=496
  _globals['_ECGINITREQUEST']._serialized_end=526
  _globals['_ECGINITRESPONSE']._serialized_start=528
  _globals['_ECGINITRESPONSE']._serialized_end=559
  _globals['_ECGTRANSFERSTARTREQ']._serialized_start=561
  _globals['_ECGTRANSFERSTARTREQ']._serialized_end=596
  _globals['_ECGTRANSFERSTARTACK']._serialized_start=598
  _globals['_ECGTRANSFERSTARTACK']._serialized_end=633
  _globals['_ECGFILE']._serialized_start=635
  _globals['_ECGFILE']._serialized_end=700
# @@protoc_insertion_point(module_scope)
