# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_device_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_device_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gdi_device_status.proto\x12\x11garmin_vivomovehr\"\xd1\x08\n\x13\x44\x65viceStatusService\x12\x8e\x01\n1remote_device_battery_status_changed_notification\x18\x01 \x01(\x0b\x32S.garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusChangedNotification\x12u\n$remote_device_battery_status_request\x18\x02 \x01(\x0b\x32G.garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusRequest\x12w\n%remote_device_battery_status_response\x18\x03 \x01(\x0b\x32H.garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusResponse\x12]\n\x17\x61\x63tivity_status_request\x18\x04 \x01(\x0b\x32<.garmin_vivomovehr.DeviceStatusService.ActivityStatusRequest\x12_\n\x18\x61\x63tivity_status_response\x18\x05 \x01(\x0b\x32=.garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse\x1a.\n,RemoteDeviceBatteryStatusChangedNotification\x1a\"\n RemoteDeviceBatteryStatusRequest\x1a\x89\x01\n!RemoteDeviceBatteryStatusResponse\x12\x45\n\x06status\x18\x01 \x01(\x0e\x32\x35.garmin_vivomovehr.DeviceStatusService.ResponseStatus\x12\x1d\n\x15\x63urrent_battery_level\x18\x02 \x01(\x05\x1a\x17\n\x15\x41\x63tivityStatusRequest\x1a\xb2\x01\n\x16\x41\x63tivityStatusResponse\x12\\\n\x06status\x18\x01 \x01(\x0e\x32L.garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse.ActivityStatus\":\n\x0e\x41\x63tivityStatus\x12\x07\n\x03OFF\x10\x00\x12\x0b\n\x07STOPPED\x10\x01\x12\n\n\x06PAUSED\x10\x02\x12\x06\n\x02ON\x10\x03\"K\n\x0eResponseStatus\x12\x1b\n\x17UNKNOWN_RESPONSE_STATUS\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x14\n\x10NO_REMOTE_DEVICE\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_device_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICESTATUSSERVICE']._serialized_start=47
  _globals['_DEVICESTATUSSERVICE']._serialized_end=1152
  _globals['_DEVICESTATUSSERVICE_REMOTEDEVICEBATTERYSTATUSCHANGEDNOTIFICATION']._serialized_start=647
  _globals['_DEVICESTATUSSERVICE_REMOTEDEVICEBATTERYSTATUSCHANGEDNOTIFICATION']._serialized_end=693
  _globals['_DEVICESTATUSSERVICE_REMOTEDEVICEBATTERYSTATUSREQUEST']._serialized_start=695
  _globals['_DEVICESTATUSSERVICE_REMOTEDEVICEBATTERYSTATUSREQUEST']._serialized_end=729
  _globals['_DEVICESTATUSSERVICE_REMOTEDEVICEBATTERYSTATUSRESPONSE']._serialized_start=732
  _globals['_DEVICESTATUSSERVICE_REMOTEDEVICEBATTERYSTATUSRESPONSE']._serialized_end=869
  _globals['_DEVICESTATUSSERVICE_ACTIVITYSTATUSREQUEST']._serialized_start=871
  _globals['_DEVICESTATUSSERVICE_ACTIVITYSTATUSREQUEST']._serialized_end=894
  _globals['_DEVICESTATUSSERVICE_ACTIVITYSTATUSRESPONSE']._serialized_start=897
  _globals['_DEVICESTATUSSERVICE_ACTIVITYSTATUSRESPONSE']._serialized_end=1075
  _globals['_DEVICESTATUSSERVICE_ACTIVITYSTATUSRESPONSE_ACTIVITYSTATUS']._serialized_start=1017
  _globals['_DEVICESTATUSSERVICE_ACTIVITYSTATUSRESPONSE_ACTIVITYSTATUS']._serialized_end=1075
  _globals['_DEVICESTATUSSERVICE_RESPONSESTATUS']._serialized_start=1077
  _globals['_DEVICESTATUSSERVICE_RESPONSESTATUS']._serialized_end=1152
# @@protoc_insertion_point(module_scope)
