# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_app_config_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_app_config_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgdi_app_config_service.proto\x12\x11garmin_vivomovehr\"\xe4\x03\n\x10\x41ppConfigService\x12\x43\n\x0c\x61ppConfigGet\x18\x01 \x01(\x0b\x32-.garmin_vivomovehr.AppConfigService.AppConfig\x12O\n\x12\x61ppConfigGetStatus\x18\x02 \x01(\x0b\x32\x33.garmin_vivomovehr.AppConfigService.appConfigStatus\x12\x43\n\x0c\x61ppConfigSet\x18\x03 \x01(\x0b\x32-.garmin_vivomovehr.AppConfigService.AppConfig\x12O\n\x12\x61ppConfigSetStatus\x18\x04 \x01(\x0b\x32\x33.garmin_vivomovehr.AppConfigService.appConfigStatus\x12\x43\n\x0c\x61ppConfigRet\x18\x05 \x01(\x0b\x32-.garmin_vivomovehr.AppConfigService.AppConfig\x1a\x30\n\x0f\x61ppConfigStatus\x12\r\n\x05\x61ppId\x18\x01 \x02(\x0c\x12\x0e\n\x06status\x18\x02 \x01(\r\x1a-\n\tAppConfig\x12\r\n\x05\x61ppId\x18\x01 \x02(\x0c\x12\x11\n\tappConfig\x18\x02 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_app_config_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPCONFIGSERVICE']._serialized_start=52
  _globals['_APPCONFIGSERVICE']._serialized_end=536
  _globals['_APPCONFIGSERVICE_APPCONFIGSTATUS']._serialized_start=441
  _globals['_APPCONFIGSERVICE_APPCONFIGSTATUS']._serialized_end=489
  _globals['_APPCONFIGSERVICE_APPCONFIG']._serialized_start=491
  _globals['_APPCONFIGSERVICE_APPCONFIG']._serialized_end=536
# @@protoc_insertion_point(module_scope)
