# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_find_my_watch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_find_my_watch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gdi_find_my_watch.proto\x12\x11garmin_vivomovehr\"\xae\x05\n\x12\x46indMyWatchService\x12N\n\x0c\x66ind_request\x18\x01 \x01(\x0b\x32\x38.garmin_vivomovehr.FindMyWatchService.FindMyWatchRequest\x12P\n\rfind_response\x18\x02 \x01(\x0b\x32\x39.garmin_vivomovehr.FindMyWatchService.FindMyWatchResponse\x12V\n\x0e\x63\x61ncel_request\x18\x03 \x01(\x0b\x32>.garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelRequest\x12X\n\x0f\x63\x61ncel_response\x18\x04 \x01(\x0b\x32?.garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelResponse\x1a%\n\x12\x46indMyWatchRequest\x12\x0f\n\x07timeout\x18\x01 \x02(\x05\x1a[\n\x13\x46indMyWatchResponse\x12\x44\n\x06status\x18\x01 \x01(\x0e\x32\x34.garmin_vivomovehr.FindMyWatchService.ResponseStatus\x1a\x1a\n\x18\x46indMyWatchCancelRequest\x1a\x61\n\x19\x46indMyWatchCancelResponse\x12\x44\n\x06status\x18\x01 \x01(\x0e\x32\x34.garmin_vivomovehr.FindMyWatchService.ResponseStatus\"A\n\x0eResponseStatus\x12\x1b\n\x17UNKNOWN_RESPONSE_STATUS\x10\x00\x12\x06\n\x02OK\x10\x64\x12\n\n\x05\x45RROR\x10\xc8\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_find_my_watch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINDMYWATCHSERVICE']._serialized_start=47
  _globals['_FINDMYWATCHSERVICE']._serialized_end=733
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHREQUEST']._serialized_start=409
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHREQUEST']._serialized_end=446
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHRESPONSE']._serialized_start=448
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHRESPONSE']._serialized_end=539
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHCANCELREQUEST']._serialized_start=541
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHCANCELREQUEST']._serialized_end=567
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHCANCELRESPONSE']._serialized_start=569
  _globals['_FINDMYWATCHSERVICE_FINDMYWATCHCANCELRESPONSE']._serialized_end=666
  _globals['_FINDMYWATCHSERVICE_RESPONSESTATUS']._serialized_start=668
  _globals['_FINDMYWATCHSERVICE_RESPONSESTATUS']._serialized_end=733
# @@protoc_insertion_point(module_scope)
