# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_sms_notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_sms_notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1agdi_sms_notification.proto\x12\x11garmin_vivomovehr\"\xb2\n\n\x16SmsNotificationService\x12\x61\n\x18sms_send_message_request\x18\x01 \x01(\x0b\x32?.garmin_vivomovehr.SmsNotificationService.SmsSendMessageRequest\x12\x63\n\x19sms_send_message_response\x18\x02 \x01(\x0b\x32@.garmin_vivomovehr.SmsNotificationService.SmsSendMessageResponse\x12x\n$sms_canned_list_changed_notification\x18\x03 \x01(\x0b\x32J.garmin_vivomovehr.SmsNotificationService.SmsCannedListChangedNotification\x12_\n\x17sms_canned_list_request\x18\x04 \x01(\x0b\x32>.garmin_vivomovehr.SmsNotificationService.SmsCannedListRequest\x12\x61\n\x18sms_canned_list_response\x18\x05 \x01(\x0b\x32?.garmin_vivomovehr.SmsNotificationService.SmsCannedListResponse\x1a\x41\n\x15SmsSendMessageRequest\x12\x17\n\x0freceiver_number\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x1a\x62\n\x16SmsSendMessageResponse\x12H\n\x06status\x18\x01 \x01(\x0e\x32\x38.garmin_vivomovehr.SmsNotificationService.ResponseStatus\x1ar\n SmsCannedListChangedNotification\x12N\n\x0c\x63hanged_type\x18\x01 \x03(\x0e\x32\x38.garmin_vivomovehr.SmsNotificationService.CannedListType\x1ai\n\x14SmsCannedListRequest\x12Q\n\x0frequested_types\x18\x01 \x03(\x0e\x32\x38.garmin_vivomovehr.SmsNotificationService.CannedListType\x1a\xa9\x01\n\x15SmsCannedListResponse\x12H\n\x06status\x18\x01 \x01(\x0e\x32\x38.garmin_vivomovehr.SmsNotificationService.ResponseStatus\x12\x46\n\x05lists\x18\x02 \x03(\x0b\x32\x37.garmin_vivomovehr.SmsNotificationService.SmsCannedList\x1ai\n\rSmsCannedList\x12\x46\n\x04type\x18\x01 \x01(\x0e\x32\x38.garmin_vivomovehr.SmsNotificationService.CannedListType\x12\x10\n\x08response\x18\x02 \x03(\t\"C\n\x0e\x43\x61nnedListType\x12\x17\n\x13PHONE_CALL_RESPONSE\x10\x00\x12\x18\n\x14SMS_MESSAGE_RESPONSE\x10\x01\"0\n\x0eResponseStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\rGENERIC_ERROR\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_sms_notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMSNOTIFICATIONSERVICE']._serialized_start=50
  _globals['_SMSNOTIFICATIONSERVICE']._serialized_end=1380
  _globals['_SMSNOTIFICATIONSERVICE_SMSSENDMESSAGEREQUEST']._serialized_start=594
  _globals['_SMSNOTIFICATIONSERVICE_SMSSENDMESSAGEREQUEST']._serialized_end=659
  _globals['_SMSNOTIFICATIONSERVICE_SMSSENDMESSAGERESPONSE']._serialized_start=661
  _globals['_SMSNOTIFICATIONSERVICE_SMSSENDMESSAGERESPONSE']._serialized_end=759
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLISTCHANGEDNOTIFICATION']._serialized_start=761
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLISTCHANGEDNOTIFICATION']._serialized_end=875
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLISTREQUEST']._serialized_start=877
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLISTREQUEST']._serialized_end=982
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLISTRESPONSE']._serialized_start=985
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLISTRESPONSE']._serialized_end=1154
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLIST']._serialized_start=1156
  _globals['_SMSNOTIFICATIONSERVICE_SMSCANNEDLIST']._serialized_end=1261
  _globals['_SMSNOTIFICATIONSERVICE_CANNEDLISTTYPE']._serialized_start=1263
  _globals['_SMSNOTIFICATIONSERVICE_CANNEDLISTTYPE']._serialized_end=1330
  _globals['_SMSNOTIFICATIONSERVICE_RESPONSESTATUS']._serialized_start=1332
  _globals['_SMSNOTIFICATIONSERVICE_RESPONSESTATUS']._serialized_end=1380
# @@protoc_insertion_point(module_scope)
