# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_notifications_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_notifications_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fgdi_notifications_service.proto\x12\x11garmin_vivomovehr\"\x8e\x01\n\x14NotificationsService\x12\x39\n\x0epictureRequest\x18\x01 \x01(\x0b\x32!.garmin_vivomovehr.PictureRequest\x12;\n\x0fpictureResponse\x18\x02 \x01(\x0b\x32\".garmin_vivomovehr.PictureResponse\"q\n\x0ePictureRequest\x12\x17\n\x0fnotification_id\x18\x01 \x01(\r\x12\x0c\n\x04unk2\x18\x02 \x01(\r\x12\x38\n\nparameters\x18\x03 \x01(\x0b\x32$.garmin_vivomovehr.PictureParameters\"Q\n\x11PictureParameters\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0c\n\x04unk3\x18\x03 \x01(\r\x12\x0f\n\x07quality\x18\x04 \x01(\r\"\x93\x01\n\x0fPictureResponse\x12\x0c\n\x04unk1\x18\x01 \x01(\r\x12\x17\n\x0fnotification_id\x18\x02 \x01(\r\x12\x0c\n\x04unk3\x18\x03 \x01(\r\x12\x0c\n\x04unk4\x18\x04 \x01(\r\x12=\n\x10\x64\x61taTransferItem\x18\x05 \x01(\x0b\x32#.garmin_vivomovehr.DataTransferItem\",\n\x10\x44\x61taTransferItem\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04size\x18\x02 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_notifications_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONSSERVICE']._serialized_start=55
  _globals['_NOTIFICATIONSSERVICE']._serialized_end=197
  _globals['_PICTUREREQUEST']._serialized_start=199
  _globals['_PICTUREREQUEST']._serialized_end=312
  _globals['_PICTUREPARAMETERS']._serialized_start=314
  _globals['_PICTUREPARAMETERS']._serialized_end=395
  _globals['_PICTURERESPONSE']._serialized_start=398
  _globals['_PICTURERESPONSE']._serialized_end=545
  _globals['_DATATRANSFERITEM']._serialized_start=547
  _globals['_DATATRANSFERITEM']._serialized_end=591
# @@protoc_insertion_point(module_scope)
