# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_smart_proto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_smart_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import gdi_authentication_service_pb2 as gdi__authentication__service__pb2
from . import gdi_device_status_pb2 as gdi__device__status__pb2
from . import gdi_file_sync_service_pb2 as gdi__file__sync__service__pb2
from . import gdi_find_my_watch_pb2 as gdi__find__my__watch__pb2
from . import gdi_core_pb2 as gdi__core__pb2
from . import gdi_http_service_pb2 as gdi__http__service__pb2
from . import gdi_app_config_service_pb2 as gdi__app__config__service__pb2
from . import gdi_installed_apps_service_pb2 as gdi__installed__apps__service__pb2
from . import gdi_data_transfer_service_pb2 as gdi__data__transfer__service__pb2
from . import gdi_sms_notification_pb2 as gdi__sms__notification__pb2
from . import gdi_calendar_service_pb2 as gdi__calendar__service__pb2
from . import gdi_settings_service_pb2 as gdi__settings__service__pb2
from . import gdi_notifications_service_pb2 as gdi__notifications__service__pb2
from . import gdi_ecg_service_pb2 as gdi__ecg__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gdi_smart_proto.proto\x12\x11garmin_vivomovehr\x1a gdi_authentication_service.proto\x1a\x17gdi_device_status.proto\x1a\x1bgdi_file_sync_service.proto\x1a\x17gdi_find_my_watch.proto\x1a\x0egdi_core.proto\x1a\x16gdi_http_service.proto\x1a\x1cgdi_app_config_service.proto\x1a gdi_installed_apps_service.proto\x1a\x1fgdi_data_transfer_service.proto\x1a\x1agdi_sms_notification.proto\x1a\x1agdi_calendar_service.proto\x1a\x1agdi_settings_service.proto\x1a\x1fgdi_notifications_service.proto\x1a\x15gdi_ecg_service.proto\"\x9e\x07\n\x05Smart\x12<\n\x10\x63\x61lendar_service\x18\x01 \x01(\x0b\x32\".garmin_vivomovehr.CalendarService\x12\x34\n\x0chttp_service\x18\x02 \x01(\x0b\x32\x1e.garmin_vivomovehr.HttpService\x12?\n\x12\x61pp_config_service\x18\x04 \x01(\x0b\x32#.garmin_vivomovehr.AppConfigService\x12G\n\x16installed_apps_service\x18\x03 \x01(\x0b\x32\'.garmin_vivomovehr.InstalledAppsService\x12\x45\n\x15\x64\x61ta_transfer_service\x18\x07 \x01(\x0b\x32&.garmin_vivomovehr.DataTransferService\x12\x45\n\x15\x64\x65vice_status_service\x18\x08 \x01(\x0b\x32&.garmin_vivomovehr.DeviceStatusService\x12\x44\n\x15\x66ind_my_watch_service\x18\x0c \x01(\x0b\x32%.garmin_vivomovehr.FindMyWatchService\x12\x34\n\x0c\x63ore_service\x18\r \x01(\x0b\x32\x1e.garmin_vivomovehr.CoreService\x12K\n\x18sms_notification_service\x18\x10 \x01(\x0b\x32).garmin_vivomovehr.SmsNotificationService\x12G\n\x15\x61uthenticationService\x18\x1b \x01(\x0b\x32(.garmin_vivomovehr.AuthenticationService\x12\x32\n\x0b\x65\x63g_service\x18\' \x01(\x0b\x32\x1d.garmin_vivomovehr.EcgService\x12<\n\x10settings_service\x18* \x01(\x0b\x32\".garmin_vivomovehr.SettingsService\x12=\n\x11\x66ile_sync_service\x18+ \x01(\x0b\x32\".garmin_vivomovehr.FileSyncService\x12\x46\n\x15notifications_service\x18\x31 \x01(\x0b\x32\'.garmin_vivomovehr.NotificationsService')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_smart_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMART']._serialized_start=435
  _globals['_SMART']._serialized_end=1361
# @@protoc_insertion_point(module_scope)
