# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gdi_data_transfer_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gdi_data_transfer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fgdi_data_transfer_service.proto\x12\x11garmin_vivomovehr\"\xdf\x03\n\x13\x44\x61taTransferService\x12W\n\x13\x64\x61taDownloadRequest\x18\x01 \x01(\x0b\x32:.garmin_vivomovehr.DataTransferService.DataDownloadRequest\x12Y\n\x14\x64\x61taDownloadResponse\x18\x02 \x01(\x0b\x32;.garmin_vivomovehr.DataTransferService.DataDownloadResponse\x1aG\n\x13\x44\x61taDownloadRequest\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0e\n\x06offset\x18\x02 \x02(\r\x12\x14\n\x0cmaxChunkSize\x18\x03 \x01(\r\x1a\x82\x01\n\x14\x44\x61taDownloadResponse\x12=\n\x06status\x18\x01 \x02(\x0e\x32-.garmin_vivomovehr.DataTransferService.Status\x12\n\n\x02id\x18\x02 \x02(\r\x12\x0e\n\x06offset\x18\x03 \x02(\r\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"F\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0e\n\nINVALID_ID\x10\x02\x12\x12\n\x0eINVALID_OFFSET\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gdi_data_transfer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATRANSFERSERVICE']._serialized_start=55
  _globals['_DATATRANSFERSERVICE']._serialized_end=534
  _globals['_DATATRANSFERSERVICE_DATADOWNLOADREQUEST']._serialized_start=258
  _globals['_DATATRANSFERSERVICE_DATADOWNLOADREQUEST']._serialized_end=329
  _globals['_DATATRANSFERSERVICE_DATADOWNLOADRESPONSE']._serialized_start=332
  _globals['_DATATRANSFERSERVICE_DATADOWNLOADRESPONSE']._serialized_end=462
  _globals['_DATATRANSFERSERVICE_STATUS']._serialized_start=464
  _globals['_DATATRANSFERSERVICE_STATUS']._serialized_end=534
# @@protoc_insertion_point(module_scope)
